#%RAML 1.0 NamedExample
value:  |
    [
      {
        "products": [
                {
                  "productId": "1234",
                  "number": 1,
                  "MRP": 500       
                },
                {
                  "productId": "1235",
                  "number": 2,
                  "MRP": 1000         
                }
              ],
        "shippingCharges": 50,
        "totalPrice": 2550
      }
    ]