#%RAML 1.0 NamedExample

value: |
        [                  
          {
            "custID": "101",
            "cartID": "111",

            "products": [
                {
                  "productId": "1234",
                  "number": 1,
                  "MRP": 500         
                },
                {
                  "productId": "1235",
                  "number": 2,
                  "MRP": 1000         
                }
              ],
            
            "shippingCharges": 50

           }
         ]