#%RAML 1.0 NamedExample
value: |
  {
     "products": [
          {
            "productId": "1234",
            "number": 4,
            "MRP": 500
          },
          {
            "productId": "1235",
            "number": 2,
            "MRP": 51000         
          }
     ],
          
      "shippingCharges": 50,
      "paymentMethod": "COD"
      
   }